# Generated by Django 4.2.8 on 2025-05-31 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAccounts',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=155)),
                ('middle_name', models.CharField(blank=True, max_length=155, null=True)),
                ('last_name', models.CharField(max_length=155)),
                ('full_name', models.CharField(max_length=310)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('verification_token', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'adminaccounts_tbl',
            },
        ),
        migrations.CreateModel(
            name='GuestAccounts',
            fields=[
                ('guest_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=155)),
                ('middle_name', models.CharField(blank=True, max_length=155, null=True)),
                ('last_name', models.CharField(max_length=155)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('full_name', models.CharField(max_length=310)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('verification_token', models.CharField(blank=True, max_length=255, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'guestaccounts_tbl',
            },
        ),
        migrations.CreateModel(
            name='ManageGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=155)),
                ('status', models.CharField(max_length=20)),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('expected_arrival', models.DateTimeField()),
                ('payment_status', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='crud.guestaccounts')),
            ],
            options={
                'db_table': 'manageguest_tbl',
            },
        ),
        migrations.CreateModel(
            name='ManageRoom',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_type', models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('suite', 'Suite'), ('deluxe', 'Deluxe')], max_length=100)),
                ('room_number', models.CharField(max_length=50, unique=True)),
                ('bed_count', models.IntegerField()),
                ('floor', models.CharField(max_length=50)),
                ('room_status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('occupied', 'Occupied')], max_length=30)),
                ('room_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('check_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='check_in_room', to='crud.manageguest')),
            ],
            options={
                'db_table': 'manageroom_tbl',
            },
        ),
        migrations.AddField(
            model_name='manageguest',
            name='room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='crud.manageroom'),
        ),
    ]
