# Generated by Django 4.2.8 on 2025-06-02 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manageroom',
            name='room_status',
            field=models.CharField(choices=[('available', 'Available'), ('maintenance', 'Maintenance'), ('cleaning', 'Cleaning'), ('reserved', 'Reserved'), ('occupied', 'Occupied')], max_length=30),
        ),
    ]
