# Generated by Django 4.2.8 on 2025-06-11 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestaccounts',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
