# Generated by Django 4.2.8 on 2025-06-12 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_guestaccounts_card_expiry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manageroom',
            name='check_in',
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='stripe_client_secret',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='manageroom',
            name='available_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='manageroom',
            name='room_status',
            field=models.CharField(choices=[('available', 'Available'), ('maintenance', 'Maintenance'), ('cleaning', 'Cleaning'), ('reserved', 'Reserved'), ('occupied', 'Occupied')], default='available', max_length=30),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crud.guestaccounts'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_method',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
