# Generated by Django 4.2.8 on 2025-06-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_manageguest_guest_count_manageguest_payment_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manageroom',
            name='room_price_type',
            field=models.CharField(choices=[('per hour', 'Per Hour'), ('per day/night', 'Per Day/Night'), ('custom', 'Custom Price')], default='custom', max_length=100),
            preserve_default=False,
        ),
    ]
