# Generated by Django 4.2.8 on 2025-06-14 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_remove_manageroom_check_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manageguest',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Credit/Debit Card')], default='cash', max_length=20),
        ),
    ]
