# Generated by Django 4.2.8 on 2025-06-07 11:40

from django.db import migrations

def set_room_price_type_for_existing_records(apps, schema_editor):
    Manageroom = apps.get_model('crud', 'Manageroom')
    Manageroom.objects.filter(room_price_type__isnull=True).update(room_price_type='per day/night')
    Manageroom.objects.filter(room_price_type='per hour').update(room_price_type='per hour')
    Manageroom.objects.filter(room_price_type='custom').update(room_price_type='custom')
    Manageroom.objects.filter(room_price_type='per day/night').update(room_price_type='per day/night')

class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_manageroom_room_price_type'),
    ]

    operations = [
        migrations.RunPython(set_room_price_type_for_existing_records),
    ]
