# Generated by Django 4.2.8 on 2025-06-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_auto_20250607_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manageguest',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=40),
        ),
    ]
