# Generated by Django 4.2.8 on 2025-06-14 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_alter_manageguest_payment_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestaccounts',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='guestaccounts',
            name='verification_token',
        ),
    ]
