# Generated by Django 4.2.8 on 2025-06-14 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_remove_guestaccounts_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminaccounts',
            name='verification_token',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='stripe_client_secret',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='stripe_payment_intent_id',
        ),
    ]
