# Generated by Django 4.2.8 on 2025-06-14 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_remove_adminaccounts_verification_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manageguest',
            name='guest_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='crud.guestaccounts'),
        ),
    ]
