# Generated by Django 4.2.8 on 2025-06-15 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0008_alter_manageguest_guest_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestaccounts',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
