# Generated by Django 4.2.8 on 2025-06-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_alter_manageroom_room_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='manageguest',
            name='guest_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='manageguest',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Credit/Debit Card'), ('gcash', 'GCash')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='manageguest',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=40),
        ),
    ]
